# <div style="text-align: center;">Project 2: Cluster Analysis</div>

# 1. Problem Description (Business Understanding) [10 points]
[3 points]
Describe the Problem: 
- What is COVID-19, and what is social distancing and flattening the curve? 
- Why is it important to look at data about the virus spread, hospitalizations, and available resources? 

[7 point]
- Choose a stakeholder for whom you analyze and, later on, model the data. 
- Define some questions that are important for this stakeholder. 
- What decisions can your stakeholders make, and how would they affect COVID-19 outcomes? 
- Brainstorm this a lot since this choice will guide your exploration of this and all the following projects. 
- Make sure you can produce actionable recommendations for these questions using your data later in your report.

## 1 Problem Description
##### 1.1 *What is COVID-19, and what are social distancing and flattening the curve?*
- **COVID-19**, caused by the SARS-CoV-2 virus, is a respiratory illness that emerged in late 2019 and led to a global pandemic. It spreads primarily through respiratory droplets and airborne transmission, causing symptoms ranging from mild respiratory issues to severe complications such as pneumonia, organ failure, and death, particularly in high-risk populations ([cdc.gov](https://www.cdc.gov/covid/about/index.html?CDC_AA_refVal=https%3A%2F%2Fwww.cdc.gov%2Fcoronavirus%2F2019-ncov%2Fprevent-getting-sick%2Fhow-covid-spreads.html)). 

- **Social distancing** refers to reducing close physical interactions between individuals to prevent viral spread. This includes staying at least six feet apart, avoiding large gatherings, and minimizing non-essential travel ([who.int](https://www.who.int/emergencies/diseases/novel-coronavirus-2019/advice-for-public)).

- **Flattening the curve** refers to implementing measures, such as social distancing, mask mandates, lockdowns, and remote work policies, to slow the virus's spread. The goal is to reduce the peak number of cases, preventing healthcare systems from becoming overwhelmed and ensuring medical resources remain available for critical patients and preventing healthcare systems from being overwhelmed (source: [michiganmedicine.org](https://www.michiganmedicine.org/health-lab/flattening-curve-covid-19-what-does-it-mean-and-how-can-you-help?)).

##### 1.2 *Why is it important to look at data about the virus spread, hospitalizations, and available resources?*
Analyzing COVID-19 data is essential for evidence-based decision-making in public health. Monitoring infection rates, hospital capacity, and medical resource availability helps in:
- Identifying outbreak hotspots – Tracking new cases allows health agencies to implement targeted restrictions before widespread community transmission occurs ([jhu.edu](https://coronavirus.jhu.edu/data)).
- Resource allocation – Data on hospitalizations guide the distribution of ICU beds, ventilators, and medical personnel where they are needed most ([nih.gov](https://www.nhlbi.nih.gov/covid)).
- Assessing policy effectiveness – Evaluating trends before and after interventions (e.g., lockdowns, mask mandates, and vaccine rollouts) determines which strategies work best ([researchunc.edu](https://research.unc.edu/2020/10/01/the-importance-of-covid-19-data-collection-and-transmission)).
- Protecting vulnerable populations – Disaggregated data by age, race, socioeconomic status, and pre-existing conditions ensure at-risk groups receive priority care and vaccinations ([cdc.gov](https://covid.cdc.gov/covid-data-tracker/#datatracker-home)).

##### 1.3 *Choose a stakeholder for whom you analyze and, later on, model the data*
- The chosen stakeholder for this analysis is the **Texas Department of State Health Services (DSHS)** ([DSHS](https://www.dshs.texas.gov/)). DSHS is responsible for monitoring and managing public health policies, coordinating COVID-19 responses, and allocating medical resources across all Texas counties. The agency works closely with local public health departments, such as Dallas County Health and Human Services (DCHHS), to implement interventions at both the state and county levels ([DCHSS](https://www.dallascounty.org/departments/dchhs)).
- This stakeholder is ideal for this analysis because:
    - DSHS oversees statewide pandemic response efforts, making it responsible for policy decisions that impact all Texas residents.
    - The agency allocates resources (e.g., vaccines, ventilators, funding) across urban and rural counties with varying healthcare capacities.
    - DSHS collaborates with local agencies like DCHHS to manage regional outbreaks, making Dallas County a relevant case study for assessing local policy effectiveness within the state.

##### 1.4 *Define some questions that are important for this stakeholder.*
To effectively support DSHS in decision-making, this analysis focuses on the following key questions:  
1. **Which Texas counties exhibit the highest COVID-19 infection and mortality rates per capita, and how do demographic factors (e.g., population size, income levels) correlate with these trends?**  
   - *Rationale*: Enables prioritization of state and/or federal resources to high-risk regions.  
2. **How does social distancing compliance (measured via mobility data, such as percent change from baseline in retail and recreation, grocery and pharmacy, transit stations, workplaces, and residential areas) differ between urban and rural counties, and how does this correlate with case growth rates?**  
   - *Rationale*: Informs targeted federal guidelines for mobility restrictions based on specific mobility patterns in different regions.  
3. **Which counties have the lowest per capita access to workers staying at home, and how does this relate to COVID-19 case rates?**  
   - *Rationale*: Evaluates the impact of workplace exposure risks and social distancing compliance..  
4. **How do poverty and public assistance rates correlate with COVID-19 case and mortality rates across Texas counties?**  
   - *Rationale*: Helps assess whether economically disadvantaged counties experienced higher COVID-19 burdens and informs targeted interventions.
5. **How do vaccination rates vary across urban and rural counties with differing socioeconomic profiles, and what disparities exist in vaccine accessibility?**  
   - *Rationale*: Identifies gaps in vaccine equity to direct federal outreach efforts.

- **Why Are These Questions Important?**
    - These questions are critical because they allow DSHS to:
        - Identify and address COVID-19 hotspots to implement targeted interventions before widespread transmission occurs.
        - Allocate medical resources more efficiently based on the current needs and capacity of local hospitals.
        - Evaluate the effectiveness of public health measures to decide whether they should be intensified, relaxed, or restructured.
        - Protect vulnerable populations by ensuring that healthcare services, such as vaccination and treatment, are prioritized based on demographic risk factors.
    - Answering these questions will enable the **DSHS** to make informed, data-driven decisions that can directly improve public health outcomes across different counties in the US.

##### 1.5 *What decisions can your stakeholders make, and how would they affect COVID-19 outcomes?*
DSHS plays a critical role in pandemic response by making data-driven decisions that directly impact COVID-19 transmission, healthcare system strain, and mortality rates. Their key decision areas include:
- **Implementing or Adjusting Social Distancing Measures**
    - By analyzing infection trends, **DSHS** can tighten or relax mask mandates, capacity limits, and stay-at-home orders.
    - **Example**: During the Delta variant surge (2021), **DSHS** reinstated indoor mask mandates based on rising case counts, reducing the growth rate of hospitalizations ([dallasnews.com](https://www.dallasnews.com/news/2021/08/11/dallas-county-judge-clay-jenkins-issues-new-mandate-requiring-masks-in-schools-businesses/)).

- **Allocating Medical Resources Efficiently**
    - Hospitalization and ICU data guide staffing and resource distribution across **Dallas County** hospitals.
    - **Example**: In July 2020, **DSHS** used hospitalization data to redistribute ventilators to overwhelmed hospitals in South Texas ([texastribune.org](https://www.texastribune.org/2020/07/14/texas-hospitals-coronavirus/)).

- **Target Vaccination and Outreach Programs**
    - Demographic analysis ensures that high-risk and underserved communities receive vaccines early.
    - **Example**: **DSHS** launched community-based vaccination clinics in South Dallas to combat low vaccination rates and high case counts ([parklandhealth.org](https://www.parklandhealth.org/community-calendar/dchhs-popup-clinics-2176?utm_source=chatgpt.com)).

- **Public Health Communication Strategies**
    - Data helps shape effective health campaigns to encourage compliance with safety measures.
    - **Example**: In December 2020, **DSHS** used Google Mobility Data to warn against holiday travel surges, reducing post-holiday infection spikes ([nbcdfw.com](https://www.nbcdfw.com/news/local/holiday-travel-surge-amid-rising-covid-19-cases/2843212/)).

Each of these decisions directly affects COVID-19 outcomes by controlling transmission, reducing hospital burden, and saving lives.

##### 1.6 *What data is needed?*
For this analysis, several types of data will be necessary:
- **COVID-19 case data**: Information on the number of infections, recoveries, and deaths, segmented by location, age, and other demographics.
- **Hospitalization data**: Data on ICU capacity, ventilator use, and hospital admissions related to COVID-19.
- **Social distancing and mobility data**: Information on people's movement patterns to understand compliance with public health mandates and detect emerging risks (e.g., increased mobility during holidays).
- **Vaccination rates**: Data on vaccination coverage, particularly broken down by demographic groups, to assess disparities in vaccine access and uptake.
- **Public health intervention data**: Insights on mask mandates, social distancing measures, and other interventions, along with their timeline and geographic implementation.

By collecting and analyzing these data points, **DSHS** can develop a clearer picture of the pandemic’s impact, forecast future trends, and make decisions that mitigate harm to the community.

In [7]:
# Packages
install.packages("tidyverse")
install.packages("ggrepel")
install.packages("ggcorrplot")
install.packages("DT")
install.packages("gridExtra")
install.packages("sf")
install.packages("modeest")
install.packages("factoextra")
install.packages("kableExtra")
install.packages("reshape2")
install.packages("knitr")
install.packages("caret")
install.packages("car")
install.packages("lubridate")

# Libraries
library("tidyverse")
library("ggrepel")
library("ggcorrplot")
library("DT")
library("gridExtra")
library("sf")
library("modeest")
library("knitr")
library("factoextra")
library("reshape2")
library("kableExtra")
library("knitr")
library("stringr")
library("caret")
library("car")
library("lubridate")

The downloaded binary packages are in
	/var/folders/r1/n09vdz190pd3ml20lxw66slm0000gn/T//RtmpMaGKSS/downloaded_packages

The downloaded binary packages are in
	/var/folders/r1/n09vdz190pd3ml20lxw66slm0000gn/T//RtmpMaGKSS/downloaded_packages

The downloaded binary packages are in
	/var/folders/r1/n09vdz190pd3ml20lxw66slm0000gn/T//RtmpMaGKSS/downloaded_packages

The downloaded binary packages are in
	/var/folders/r1/n09vdz190pd3ml20lxw66slm0000gn/T//RtmpMaGKSS/downloaded_packages

The downloaded binary packages are in
	/var/folders/r1/n09vdz190pd3ml20lxw66slm0000gn/T//RtmpMaGKSS/downloaded_packages

The downloaded binary packages are in
	/var/folders/r1/n09vdz190pd3ml20lxw66slm0000gn/T//RtmpMaGKSS/downloaded_packages

The downloaded binary packages are in
	/var/folders/r1/n09vdz190pd3ml20lxw66slm0000gn/T//RtmpMaGKSS/downloaded_packages

The downloaded binary packages are in
	/var/folders/r1/n09vdz190pd3ml20lxw66slm0000gn/T//RtmpMaGKSS/downloaded_packages

The downloaded binary packages are in
	/var/folders/r1/n09vdz190pd3ml20lxw66slm0000gn/T//RtmpMaGKSS/downloaded_packages

The downloaded binary packages are in
	/var/folders/r1/n09vdz190pd3ml20lxw66slm0000gn/T//RtmpMaGKSS/downloaded_packages

The downloaded binary packages are in
	/var/folders/r1/n09vdz190pd3ml20lxw66slm0000gn/T//RtmpMaGKSS/downloaded_packages

The downloaded binary packages are in
	/var/folders/r1/n09vdz190pd3ml20lxw66slm0000gn/T//RtmpMaGKSS/downloaded_packages

The downloaded binary packages are in
	/var/folders/r1/n09vdz190pd3ml20lxw66slm0000gn/T//RtmpMaGKSS/downloaded_packages

The downloaded binary packages are in
	/var/folders/r1/n09vdz190pd3ml20lxw66slm0000gn/T//RtmpMaGKSS/downloaded_packages

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘gridExtra’


The following object is masked from ‘package:dplyr’:

    combine


Linking to GEOS 3.13.0, GDAL 3.8.5, PROJ 9.5.1; sf_use_s2() is TRUE

Welcome! Want to learn more? See two factoextra-related books at https://goo.gl/ve3WBa


Attaching package: ‘reshape2’


The following object is masked from ‘package:tidyr’:

    smiths



Attaching package: ‘kableExtra’


The following object is masked from ‘package:dplyr’:

    group_rows


Loading required package: lattice


Attaching package: ‘caret’


The following object is masked from ‘package:purrr’:

    lift


Loading required package: carData


Attaching package: ‘car’


The following object is masked from ‘package:dplyr’:

    recode


The following object is masked from ‘package:purrr’:

    some

In [18]:
# Define base directory
#base_dir <- "../../../../../../../Desktop/COVID-19/"
#base_dir <- "C:/Users/leona/OneDrive/CSMS/Data Mining (CS7331)/Projects/Project 1/COVID-19/"
base_dir <- "/Users/salissa/Desktop/Data Mining/Datasets/COVID-19"

# Read all CSVs in the folder into a named list
file_paths <- list.files(base_dir, pattern = "\\.csv$", full.names = TRUE)
file_names <- tools::file_path_sans_ext(basename(file_paths))
datasets <- setNames(lapply(file_paths, read.csv), file_names)

cat("\n--- All datasets successfully loaded! ---\n")

--- All datasets successfully loaded! ---

In [26]:
# randomly display 10 rows from each dataset
lapply(datasets, function(df) {
  cat("---- Sample from dataset ----\n")
  print(sample_n(df, 10))
})

---- Sample from dataset ----
   county_fips_code       county_name state state_fips_code       date
1             27009     Benton County    MN              27 2021-01-19
2             27165   Watonwan County    MN              27 2021-01-19
3             20115     Marion County    KS              20 2021-01-19
4             48011  Armstrong County    TX              48 2021-01-19
5             12045       Gulf County    FL              12 2021-01-19
6             55111       Sauk County    WI              55 2021-01-19
7             21075     Fulton County    KY              21 2021-01-19
8             23003  Aroostook County    ME              23 2021-01-19
9             21203 Rockcastle County    KY              21 2021-01-19
10            20079     Harvey County    KS              20 2021-01-19
   confirmed_cases deaths geo_id nonfamily_households family_households
1             4201     86  27009                 5614             10391
2             1066      8  27165                 1575              2752
3              871      6  20115                 1544              3313
4              128      6  48011                  162               540
5             1561     31  12045                 1615              3680
6             5111     34  55111                 8662             17016
7              411      4  21075                  961              1502
8              943     24  23003                11138             18706
9             1109     12  21203                 1831              4721
10            3218     36  20079                 4082              9273
   median_year_structure_built rent_burden_not_computed rent_over_50_percent
1                         1982                      154                 1138
2                         1951                      111                  204
3                         1956                      104                  116
4                         1963                       20                   20
5                         1987                      219                  378
6                         1981                      605                 1612
7                         1969                      121                  191
8                         1970                      991                 1640
9                         1988                      322                  321
10                        1968                      193                  863
   rent_40_to_50_percent rent_35_to_40_percent rent_30_to_35_percent
1                    516                   270                   632
2                     33                    24                    67
3                     39                    26                    65
4                      0                     0                    13
5                     83                    31                    27
6                    699                   556                   751
7                     85                    73                    27
8                    645                   424                   728
9                     51                    95                    91
10                   301                   242                   343
   rent_25_to_30_percent rent_20_to_25_percent rent_15_to_20_percent
1                    573                   613                   574
2                    104                   108                   269
3                    117                   116                   153
4                      0                    10                    38
5                    254                   115                    65
6                    719                   968                  1039
7                     93                   104                    56
8                   1276                   837                   741
9                    123                   262                   165
10                   298                   489                   619
   rent_10_to_15_percent rent_under_10_percent total_pop male_pop female_pop
1                    297                   240     39360    19652      19708
2                    152                    74     10936     5511       5425
3                    112                   120     12087     5997       6090
4                     20                    12      1929      974        955
5                    131                    39     16018     9595       6423
6                    758                   329     63340    31555      31785
7                    153                    54      6259     3094       3165
8                    758                   410     68840    34006      34834
9                     79                    68     16815     8168       8647
10                   425                   137     34683    17016      17667
   median_age white_pop black_pop asian_pop hispanic_pop amerindian_pop
1        35.6     36008      1104       425          852            135
2        39.9      8091        59       106         2553             19
3        45.0     11266        80        35          400              7
4        45.9      1671        24         0          192             26
5        44.3     11928      2694        91          762             73
6        41.3     57848       444       437         3060            686
7        43.1      4456      1526        11           44              7
8        47.2     65024       620       280          767           1171
9        42.2     16394        34         9          142            168
10       39.2     28874       638       211         4052             94
   other_race_pop two_or_more_races_pop not_hispanic_pop
1               3                   833            38508
2               0                   108             8383
3               0                   299            11687
4               0                    16             1737
5              14                   424            15256
6              56                   809            60280
7               4                   211             6215
8               4                   970            68073
9               0                    68            16673
10              0                   761            30631
   commuters_by_public_transportation households median_income
1                                 258      16005         53574
2                                  22       4327         50044
3                                   0       4857         50212
4                                   0        702         68750
5                                   2       5295         44647
6                                  52      25678         54447
7                                  19       2463         28274
8                                  26      29844         39021
9                                  28       6552         35888
10                                  7      13355         55687
   income_per_capita housing_units vacant_housing_units
1              27018         16733                  728
2              26884          5039                  712
3              25620          5984                 1127
4              31219           922                  220
5              21085          9372                 4077
6              28331         30171                 4493
7              18111          3360                  897
8              23631         39810                 9966
9              19750          7802                 1250
10             26587         14695                 1340
   vacant_housing_units_for_rent vacant_housing_units_for_sale median_rent
1                            208                            54         634
2                              7                            89         496
3                             53                           124         392
4                             25                             6         524
5                            250                           333         681
6                            239                           412         648
7                            106                           108         331
8                           1003                           704         489
9                             57                            30         376
10                           209                           409         499
   percent_income_spent_on_rent owner_occupied_housing_units
1                          31.0                        10998
2                          21.0                         3181
3                          22.0                         3889
4                          18.2                          569
5                          29.2                         3953
6                          29.3                        17642
7                          27.7                         1506
8                          28.9                        21394
9                          27.2                         4975
10                         28.2                         9445
   million_dollar_housing_units mortgaged_housing_units
1                            14                    7507
2                             2                    1816
3                             0                    2005
4                             0                     275
5                            26                    1932
6                            38                   11275
7                             8                     573
8                            24                   11354
9                             4                    2385
10                            0                    5370
   families_with_young_children two_parent_families_with_young_children
1                          3272                                    2155
2                           948                                     575
3                           779                                     590
4                           107                                      65
5                           821                                     516
6                          4523                                    3160
7                           409                                     129
8                          3704                                    2428
9                          1097                                     686
10                         2448                                    1923
   two_parents_in_labor_force_families_with_young_children
1                                                     1512
2                                                      461
3                                                      426
4                                                       48
5                                                      295
6                                                     2245
7                                                      110
8                                                     1322
9                                                      392
10                                                     988
   two_parents_father_in_labor_force_families_with_young_children
1                                                             462
2                                                              93
3                                                             152
4                                                              17
5                                                             182
6                                                             781
7                                                              19
8                                                             939
9                                                             276
10                                                            773
   two_parents_mother_in_labor_force_families_with_young_children
1                                                             105
2                                                              15
3                                                              12
4                                                               0
5                                                               9
6                                                              78
7                                                               0
8                                                             105
9                                                              18
10                                                            155
   two_parents_not_in_labor_force_families_with_young_children
1                                                           76
2                                                            6
3                                                            0
4                                                            0
5                                                           30
6                                                           56
7                                                            0
8                                                           62
9                                                            0
10                                                           7
   one_parent_families_with_young_children
1                                     1117
2                                      373
3                                      189
4                                       42
5                                      305
6                                     1363
7                                      280
8                                     1276
9                                      411
10                                     525
   father_one_parent_families_with_young_children
1                                             307
2                                             116
3                                              67
4                                               0
5                                             100
6                                             465
7                                              43
8                                             405
9                                             103
10                                            263
   father_in_labor_force_one_parent_families_with_young_children
1                                                            300
2                                                            114
3                                                             28
4                                                              0
5                                                             69
6                                                            447
7                                                             43
8                                                            294
9                                                             86
10                                                           263
   commute_10_14_mins commute_15_19_mins commute_20_24_mins commute_25_29_mins
1                3223               3693               2899               1086
2                 685                532                333                215
3                 561                581                562                200
4                  89                 20                 36                 67
5                 877                810                496                351
6                5507               3832               3630               1904
7                 281                218                335                146
8                4679               4317               3289               1273
9                 825               1006                650                324
10               2727               1897               1435                700
   commute_30_34_mins commute_45_59_mins aggregate_travel_time_to_work
1                1898                903                        445495
2                 307                389                         94250
3                 494                420                        105765
4                 139                125                         23325
5                 757                449                        122385
6                2479               2103                        683260
7                 237                 42                         45690
8                2606                969                        500255
9                 692                476                        150470
10               1833                812                        316195
   income_less_10000 income_10000_14999 income_15000_19999 income_20000_24999
1                913                880                924                834
2                223                258                276                169
3                272                232                293                333
4                 18                 34                 26                 35
5                331                413                273                402
6               1125               1245               1330               1318
7                412                215                287                215
8               2848               2589               2373               2085
9                715                651                635                513
10               674                764                516                755
   income_25000_29999 income_30000_34999 income_35000_39999 income_40000_44999
1                 741                845                825                802
2                 256                312                226                241
3                 254                308                294                203
4                  24                 29                 22                 15
5                 250                410                303                286
6                1413               1665               1188               1297
7                 146                157                 82                 91
8                1864               1670               1824               1471
9                 298                394                338                259
10                567                634                464               1054
   income_45000_49999 income_50000_59999 income_60000_74999 income_75000_99999
1                 825               1315               1813               2237
2                 201                412                459                472
3                 229                431                619                664
4                  26                 67                 98                 89
5                 257                354                532                620
6                1091               2212               3025               3688
7                 157                161                181                164
8                1295               2263               2880               3147
9                 220                630                643                451
10                622               1292               1667               1599
   income_100000_124999 income_125000_149999 income_150000_199999
1                  1216                  756                  709
2                   441                  137                  156
3                   398                  133                  102
4                    83                   53                   64
5                   546                   43                  190
6                  2267                 1062                 1120
7                    95                   57                   32
8                  1584                  731                  768
9                   373                  273                   62
10                 1096                  853                  504
   income_200000_or_more

$c19_census
   county_fips_code       county_name state state_fips_code       date
1             27009     Benton County    MN              27 2021-01-19
2             27165   Watonwan County    MN              27 2021-01-19
3             20115     Marion County    KS              20 2021-01-19
4             48011  Armstrong County    TX              48 2021-01-19
5             12045       Gulf County    FL              12 2021-01-19
6             55111       Sauk County    WI              55 2021-01-19
7             21075     Fulton County    KY              21 2021-01-19
8             23003  Aroostook County    ME              23 2021-01-19
9             21203 Rockcastle County    KY              21 2021-01-19
10            20079     Harvey County    KS              20 2021-01-19
   confirmed_cases deaths geo_id nonfamily_households family_households
1             4201     86  27009                 5614             10391
2             1066      8  27165                 1575              2752
3              871      6  20115                 1544              3313
4              128      6  48011                  162               540
5             1561     31  12045                 1615              3680
6             5111     34  55111                 8662             17016
7              411      4  21075                  961              1502
8              943     24  23003                11138             18706
9             1109     12  21203                 1831              4721
10            3218     36  20079                 4082              9273
   median_year_structure_built rent_burden_not_computed rent_over_50_percent
1                         1982                      154                 1138
2                         1951                      111                  204
3                         1956                      104                  116
4                         1963                       20                   20
5                         1987                      219                  378
6                         1981                      605                 1612
7                         1969                      121                  191
8                         1970                      991                 1640
9                         1988                      322                  321
10                        1968                      193                  863
   rent_40_to_50_percent rent_35_to_40_percent rent_30_to_35_percent
1                    516                   270                   632
2                     33                    24                    67
3                     39                    26                    65
4                      0                     0                    13
5                     83                    31                    27
6                    699                   556                   751
7                     85                    73                    27
8                    645                   424                   728
9                     51                    95                    91
10                   301                   242                   343
   rent_25_to_30_percent rent_20_to_25_percent rent_15_to_20_percent
1                    573                   613                   574
2                    104                   108                   269
3                    117                   116                   153
4                      0                    10                    38
5                    254                   115                    65
6                    719                   968                  1039
7                     93                   104                    56
8                   1276                   837                   741
9                    123                   262                   165
10                   298                   489                   619
   rent_10_to_15_percent rent_under_10_percent total_pop male_pop female_pop
1                    297                   240     39360    19652      19708
2                    152                    74     10936     5511       5425
3                    112                   120     12087     5997       6090
4                     20                    12      1929      974        955
5                    131                    39     16018     9595       6423
6                    758                   329     63340    31555      31785
7                    153                    54      6259     3094       3165
8                    758                   410     68840    34006      34834
9                     79                    68     16815     8168       8647
10                   425                   137     34683    17016      17667
   median_age white_pop black_pop asian_pop hispanic_pop amerindian_pop
1        35.6     36008      1104       425          852            135
2        39.9      8091        59       106         2553             19
3        45.0     11266        80        35          400              7
4        45.9      1671        24         0          192             26
5        44.3     11928      2694        91          762             73
6        41.3     57848       444       437         3060            686
7        43.1      4456      1526        11           44              7
8        47.2     65024       620       280          767           1171
9        42.2     16394        34         9          142            168
10       39.2     28874       638       211         4052             94
   other_race_pop two_or_more_races_pop not_hispanic_pop
1               3                   833            38508
2               0                   108             8383
3               0                   299            11687
4               0                    16             1737
5              14                   424            15256
6              56                   809            60280
7               4                   211             6215
8               4                   970            68073
9               0                    68            16673
10              0                   761            30631
   commuters_by_public_transportation households median_income
1                                 258      16005         53574
2                                  22       4327         50044
3                                   0       4857         50212
4                                   0        702         68750
5                                   2       5295         44647
6                                  52      25678         54447
7                                  19       2463         28274
8                                  26      29844         39021
9                                  28       6552         35888
10                                  7      13355         55687
   income_per_capita housing_units vacant_housing_units
1              27018         16733                  728
2              26884          5039                  712
3              25620          5984                 1127
4              31219           922                  220
5              21085          9372                 4077
6              28331         30171                 4493
7              18111          3360                  897
8              23631         39810                 9966
9              19750          7802                 1250
10             26587         14695                 1340
   vacant_housing_units_for_rent vacant_housing_units_for_sale median_rent
1                            208                            54         634
2                              7                            89         496
3                             53                           124         392
4                             25                             6         524
5                            250                           333         681
6                            239                           412         648
7                            106                           108         331
8                           1003                           704         489
9                             57                            30         376
10                           209                           409         499
   percent_income_spent_on_rent owner_occupied_housing_units
1                          31.0                        10998
2                          21.0                         3181
3                          22.0                         3889
4                          18.2                          569
5                          29.2                         3953
6                          29.3                        17642
7                          27.7                         1506
8                          28.9                        21394
9                          27.2                         4975
10                         28.2                         9445
   million_dollar_housing_units mortgaged_housing_units
1                            14                    7507
2                             2                    1816
3                             0                    2005
4                             0                     275
5                            26                    1932
6                            38                   11275
7                             8                     573
8                            24                   11354
9                             4                    2385
10                            0                    5370
   families_with_young_children two_parent_families_with_young_children
1                          3272                                    2155
2                           948                                     575
3                           779                                     590
4                           107                                      65
5                           821                                     516
6                          4523                                    3160
7                           409                                     129
8                          3704                                    2428
9                          1097                                     686
10                         2448                                    1923
   two_parents_in_labor_force_families_with_young_children
1                                                     1512
2                                                      461
3                                                      426
4                                                       48
5                                                      295
6                                                     2245
7                                                      110
8                                                     1322
9                                                      392
10                                                     988
   two_parents_father_in_labor_force_families_with_young_children
1                                                             462
2                                                              93
3                                                             152
4                                                              17
5                                                             182
6                                                             781
7                                                              19
8                                                             939
9                                                             276
10                                                            773
   two_parents_mother_in_labor_force_families_with_young_children
1                                                             105
2                                                              15
3                                                              12
4                                                               0
5                                                               9
6                                                              78
7                                                               0
8                                                             105
9                                                              18
10                                                            155
   two_parents_not_in_labor_force_families_with_young_children
1                                                           76
2                                                            6
3                                                            0
4                                                            0
5                                                           30
6                                                           56
7                                                            0
8                                                           62
9                                                            0
10                                                           7
   one_parent_families_with_young_children
1                                     1117
2                                      373
3                                      189
4                                       42
5                                      305
6                                     1363
7                                      280
8                                     1276
9                                      411
10                                     525
   father_one_parent_families_with_young_children
1                                             307
2                                             116
3                                              67
4                                               0
5                                             100
6                                             465
7                                              43
8                                             405
9                                             103
10                                            263
   father_in_labor_force_one_parent_families_with_young_children
1                                                            300
2                                                            114
3                                                             28
4                                                              0
5                                                             69
6                                                            447
7                                                             43
8                                                            294
9                                                             86
10                                                           263
   commute_10_14_mins commute_15_19_mins commute_20_24_mins commute_25_29_mins
1                3223               3693               2899               1086
2                 685                532                333                215
3                 561                581                562                200
4                  89                 20                 36                 67
5                 877                810                496                351
6                5507               3832               3630               1904
7                 281                218                335                146
8                4679               4317               3289               1273
9                 825               1006                650                324
10               2727               1897               1435                700
   commute_30_34_mins commute_45_59_mins aggregate_travel_time_to_work
1                1898                903                        445495
2                 307                389                         94250
3                 494                420                        105765
4                 139                125                         23325
5                 757                449                        122385
6                2479               2103                        683260
7                 237                 42                         45690
8                2606                969                        500255
9                 692                476                        150470
10               1833                812                        316195
   income_less_10000 income_10000_14999 income_15000_19999 income_20000_24999
1                913                880                924                834
2                223                258                276                169
3                272                232                293                333
4                 18                 34                 26                 35
5                331                413                273                402
6               1125               1245               1330               1318
7                412                215                287                215
8               2848               2589               2373               2085
9                715                651                635                513
10               674                764                516                755
   income_25000_29999 income_30000_34999 income_35000_39999 income_40000_44999
1                 741                845                825                802
2                 256                312                226                241
3                 254                308                294                203
4                  24                 29                 22                 15
5                 250                410                303                286
6                1413               1665               1188               1297
7                 146                157                 82                 91
8                1864               1670               1824               1471
9                 298                394                338                259
10                567                634                464               1054
   income_45000_49999 income_50000_59999 income_60000_74999 income_75000_99999
1                 825               1315               1813               2237
2                 201                412                459                472
3                 229                431                619                664
4                  26                 67                 98                 89
5                 257                354                532                620
6                1091               2212               3025               3688
7                 157                161                181                164
8                1295               2263               2880               3147
9                 220                630                643                451
10                622               1292               1667               1599
   income_100000_124999 income_125000_149999 income_150000_199999
1                  1216                  756                  709
2                   441                  137                  156
3                   398                  133                  102
4                    83                   53                   64
5                   546                   43                  190
6                  2267                 1062                 1120
7                    95                   57                   32
8                  1584                  731                  768
9                   373                  273                   62
10                 1096                  853                  504
   income_200000_or_more
1                    370

In [36]:
# change datatype to factors
datasets <- lapply(datasets, function(df) {
  df %>% mutate(across(where(is.character), as.factor))
})

sapply(datasets, dim)

     c19_census c19_tx Global_Mobility
[1,] 3142       94350  3991405
[2,]  259           7       14

## 2. Data Preparation [30 points]
What are the objects you want to cluster? Describe which features you want to use for clustering and why. Add a table with all the features and basic statistics that you use for clustering (can be taken from report 1). [20]
What is the scale of measurement of the features and what are the appropriate measures for similarity/distance? [10]

3. Modeling [60 points]
Perform cluster analysis using several methods (at least k-means and hierarchical clustering) using different feature subsets. Produce at least 4 different clusterings. [30]
How did you determine a suitable number of clusters for each method? [10]
Use unsupervised evaluation to describe and compare the clusterings and the clusters (some visual methods would be good). [10]
Identify a feature you could use as the ground truth to perform supervised evaluation. Compare the clusterings using this method. [10]

4. Recommendations (Evaluation) [10 points]
Describe your results. What recommendations can you formulate based on the clustering results? How do these recommendations relate to the ones already presented in report 1?
What findings are the most interesting to your stakeholder?